version: "3.9"
services:
  unfollowers-bot:
    image: "harduex/instagram-unfollowers-bot"
    volumes:
      - instagram-unfollowers-volume:/app/data
    env_file:
      - .env

volumes:
  instagram-unfollowers-volume: 
