version: "3.9"
services:
  unfollowers-bot:
    image: "harduex/instagram-unfollowers-bot"
    volumes:
      - instagram-unfollowers-volume:/app/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - .env
    restart: on-failure

volumes:
  instagram-unfollowers-volume: 
